
spring:
  graphql:
    graphiql:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.2:3306/state_management
    username: root
    password: root

