
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug

spring:
  graphql:
    graphiql:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

warrior:
  nodejs-api-url: ${NODEJS_API_URL}

